### ISSUE TITLE
Upstreaming this

### ISSUE THREAD

**Issue by JohnRTitor** [kai-tub/uwsm-nix#1]
Hi, since hardcode mode support is complete, are you still interested to upstream this?

I was considering upstreaming [my current installation](https://github.com/JohnRTitor/nix-conf/blob/3257ebf430f7e5ed1418d2e43f5aca80b449027f/modules-overlays/uwsm/module.nix) (based on your work). But I thought I should ask first.

**Comment by kai-tub** [comment]
Thanks for asking! :heart: 
See my comments in nixpkgs #335625 :+1:
